### ISSUE TITLE
DIBaS dataset

### ISSUE THREAD

**Issue by GraninV** [gallardorafael/bacterialidentification#1]
Hi,
Thanks for a great job!
The website of the DIBaS dataset not working.
May you advise for any other source or maybe upload the dataset?
Thanks!

**Comment by gallardorafael** [comment]
Hi, GraninV, 
I realize that the original website of the DIBaS dataset is down, and I sent an email to the corresponding author of the paper, but I haven't I received an answer yet. 

I build a GitHub repository with the DIBaS dataset, but just as an alternative as I don't own the rights of the data:
https://github.com/gallardorafael/DIBaS-Dataset

I hope this will be useful for you! Let me know if you need something else.

**Comment by GraninV** [comment]
Thanks a lot, Rafael!!
